### ROTA PARA LISTAR PRODUTOS
GET http://localhost:3000/servico
Content-Type: application/json

###

### ROTA PARA CADASTRAR SERVICOS
POST http://localhost:3000/servico
Content-Type: application/json

{
    "cliente": "Gabriel",
    "endereco": "Rua jundiaí,721",
    "tipo_servico": "Manutenção",
    "data_hora": "2025-12-01T10:00:00.000Z",
    "status": "Pendente"
}

###

### EDITAR SERVICOS
PUT http://localhost:3000/servico/1
Content-Type: application/json

{
    "novoCliente": "Sérgio",
    "novoEndereco": "Rua Açu,500",
    "novoTipoServico": "Reparo",
    "novadata_hora": "2026-12-01T10:00:00.000Z",
    "novoStatus": "Concluido"
}

###

### DELETE - DELETAR PRODUTO
DELETE http://localhost:3000/servico/1
Content-Type: application/json

###